// ci_generator.go — Sajon CI/CD Workflow Generator
//
// Implements 'sajon ci github' — generates a production-ready GitHub Actions
// workflow file at .github/workflows/sajon-deploy.yml
//
// The generated workflow:
//   - Triggers on every push to main (or master)
//   - Runs 'sajon plan' on every Pull Request (dry-run, no cloud calls)
//   - Runs 'sajon up'  on push to main (live provisioning)
//   - Builds the sajon CLI from source using Go
//   - Reads cloud tokens from GitHub Secrets automatically

package emitter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// CIProvider selects which CI/CD platform to generate config for.
type CIProvider string

const (
	CIGitHub CIProvider = "github"
)

// GenerateCI creates the CI/CD configuration for the specified provider.
// It detects the current .saj file name and embeds it into the workflow.
// Returns the path of the generated file and any error.
func GenerateCI(provider CIProvider, sajFile string) (string, error) {
	switch provider {
	case CIGitHub:
		return generateGitHubActions(sajFile)
	default:
		return "", fmt.Errorf("unknown CI provider: %s (supported: github)", provider)
	}
}

// generateGitHubActions creates .github/workflows/sajon-deploy.yml
func generateGitHubActions(sajFile string) (string, error) {
	// Ensure .github/workflows/ directory exists.
	workflowDir := filepath.Join(".github", "workflows")
	if err := os.MkdirAll(workflowDir, 0755); err != nil {
		return "", fmt.Errorf("could not create .github/workflows/: %w", err)
	}

	outPath := filepath.Join(workflowDir, "sajon-deploy.yml")
	content := buildGitHubWorkflow(sajFile)

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("could not write workflow file: %w", err)
	}
	return outPath, nil
}

// buildGitHubWorkflow returns the full YAML content for the GitHub Actions workflow.
func buildGitHubWorkflow(sajFile string) string {
	if sajFile == "" {
		sajFile = "app.saj"
	}

	var sb strings.Builder

	sb.WriteString("# ╔══════════════════════════════════════════════════════════════╗\n")
	sb.WriteString("# ║           Auto-generated by Sajon CLI                        ║\n")
	sb.WriteString("# ║     sajon ci github  —  DO NOT edit manually                 ║\n")
	sb.WriteString(fmt.Sprintf("# ║     Generated: %-46s║\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")+" "))
	sb.WriteString("# ╚══════════════════════════════════════════════════════════════╝\n")
	sb.WriteString("#\n")
	sb.WriteString("# HOW TO USE:\n")
	sb.WriteString("#   1. Push this file to your GitHub repository.\n")
	sb.WriteString("#   2. Go to GitHub → Settings → Secrets and variables → Actions\n")
	sb.WriteString("#   3. Add the following Repository Secrets:\n")
	sb.WriteString("#        NEON_API_KEY              (from console.neon.tech)\n")
	sb.WriteString("#        SUPABASE_ACCESS_TOKEN     (from supabase.com/dashboard/account/tokens)\n")
	sb.WriteString("#        AWS_ACCESS_KEY_ID         (optional — only if you use AWS)\n")
	sb.WriteString("#        AWS_SECRET_ACCESS_KEY     (optional — only if you use AWS)\n")
	sb.WriteString("#   4. That's it — push to main and Sajon deploys automatically!\n")
	sb.WriteString("#\n\n")

	sb.WriteString("name: 'Sajon Cloud Deploy'\n\n")

	sb.WriteString("on:\n")
	sb.WriteString("  push:\n")
	sb.WriteString("    branches: [ main, master ]\n")
	sb.WriteString("  pull_request:\n")
	sb.WriteString("    branches: [ main, master ]\n\n")

	sb.WriteString("# Cancel any in-progress deployment when a new push arrives.\n")
	sb.WriteString("concurrency:\n")
	sb.WriteString("  group: sajon-deploy-${{ github.ref }}\n")
	sb.WriteString("  cancel-in-progress: true\n\n")

	sb.WriteString("jobs:\n\n")

	// ── Plan job (PR only) ────────────────────────────────────────────────────
	sb.WriteString("  # ── Plan: Dry-run on every Pull Request ───────────────────────\n")
	sb.WriteString("  plan:\n")
	sb.WriteString("    name: 'sajon plan (Dry Run)'\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    if: github.event_name == 'pull_request'\n\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - name: Checkout code\n")
	sb.WriteString("        uses: actions/checkout@v4\n\n")
	sb.WriteString("      - name: Set up Go\n")
	sb.WriteString("        uses: actions/setup-go@v5\n")
	sb.WriteString("        with:\n")
	sb.WriteString("          go-version: '1.22'\n\n")
	sb.WriteString("      - name: Build Sajon from source\n")
	sb.WriteString("        run: go build -o sajon .\n\n")
	sb.WriteString("      - name: Run Sajon Plan (No API Calls)\n")
	sb.WriteString(fmt.Sprintf("        run: ./sajon plan %s\n\n", sajFile))

	// ── Deploy job (push to main only) ────────────────────────────────────────
	sb.WriteString("  # ── Deploy: Provision on push to main / master ────────────────\n")
	sb.WriteString("  deploy:\n")
	sb.WriteString("    name: 'sajon up (Live Deploy)'\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    if: github.event_name == 'push' && (secrets.NEON_API_KEY != '' || secrets.SUPABASE_ACCESS_TOKEN != '')\n\n")
	sb.WriteString("    environment: production\n\n")
	sb.WriteString("    steps:\n")
	sb.WriteString("      - name: Checkout code\n")
	sb.WriteString("        uses: actions/checkout@v4\n\n")
	sb.WriteString("      - name: Set up Go\n")
	sb.WriteString("        uses: actions/setup-go@v5\n")
	sb.WriteString("        with:\n")
	sb.WriteString("          go-version: '1.22'\n\n")
	sb.WriteString("      - name: Build Sajon from source\n")
	sb.WriteString("        run: go build -o sajon .\n\n")
	sb.WriteString("      - name: Provision Infrastructure\n")
	sb.WriteString(fmt.Sprintf("        run: ./sajon up %s\n", sajFile))
	sb.WriteString("        env:\n")
	sb.WriteString("          # ── Database credentials (add these in GitHub Secrets) ──\n")
	sb.WriteString("          NEON_API_KEY:              ${{ secrets.NEON_API_KEY }}\n")
	sb.WriteString("          SUPABASE_ACCESS_TOKEN:     ${{ secrets.SUPABASE_ACCESS_TOKEN }}\n")
	sb.WriteString("          SUPABASE_ORG_ID:           ${{ secrets.SUPABASE_ORG_ID }}\n")
	sb.WriteString("          # ── AWS credentials (optional) ───────────────────────────\n")
	sb.WriteString("          AWS_ACCESS_KEY_ID:         ${{ secrets.AWS_ACCESS_KEY_ID }}\n")
	sb.WriteString("          AWS_SECRET_ACCESS_KEY:     ${{ secrets.AWS_SECRET_ACCESS_KEY }}\n")
	sb.WriteString("          AWS_DEFAULT_REGION:        ${{ secrets.AWS_DEFAULT_REGION }}\n")
	sb.WriteString("          # ── Optional: S3 remote state ────────────────────────────\n")
	sb.WriteString("          SAJON_REMOTE_BUCKET:       ${{ secrets.SAJON_REMOTE_BUCKET }}\n\n")

	sb.WriteString("      - name: Upload sajon.env as Artifact\n")
	sb.WriteString("        if: always()\n")
	sb.WriteString("        uses: actions/upload-artifact@v4\n")
	sb.WriteString("        with:\n")
	sb.WriteString("          name: sajon-env-${{ github.run_number }}\n")
	sb.WriteString("          path: sajon.env\n")
	sb.WriteString("          retention-days: 7\n")
	sb.WriteString("          if-no-files-found: ignore\n\n")

	sb.WriteString("      - name: Upload sajon.lock as Artifact\n")
	sb.WriteString("        if: always()\n")
	sb.WriteString("        uses: actions/upload-artifact@v4\n")
	sb.WriteString("        with:\n")
	sb.WriteString("          name: sajon-lock-${{ github.run_number }}\n")
	sb.WriteString("          path: sajon.lock\n")
	sb.WriteString("          retention-days: 30\n")
	sb.WriteString("          if-no-files-found: ignore\n")

	return sb.String()
}
