// env_writer.go — Sajon Auto .env Injection
//
// After 'sajon up' provisions real cloud resources (Neon, Supabase, AWS),
// this module collects all connection strings and writes them to a single
// sajon.env file in the project root.
//
// The file is written with mode 0600 (owner read/write only) so secrets
// are never exposed to other OS users.
//
// FORMAT (ready for any 12-factor app):
//
//	# Auto-generated by Sajon CLI — do not edit manually
//	# Run 'sajon up' to refresh
//	NEON_DATABASE_URL_USER_DB="postgresql://..."
//	SUPABASE_DATABASE_URL_RENTIC="postgresql://..."

package emitter

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// EnvEntry represents a single key=value line to write into sajon.env.
type EnvEntry struct {
	Key     string // e.g. NEON_DATABASE_URL_USER_DB
	Value   string // e.g. postgresql://user:pass@host/db?sslmode=require
	Comment string // optional human-readable label shown above the line
}

// WriteCloudEnvFile collects all provisioned resource connection strings and
// writes them into sajon.env (mode 0600) in the current working directory.
//
// It is designed to be called after all cloud providers have finished:
//
//	WriteCloudEnvFile(neonResults, supabaseResults, awsResults)
//
// If a previous sajon.env exists it is overwritten atomically.
// Returns nil on success; a wrapped OS error on failure.
func WriteCloudEnvFile(
	neonResults []CloudResult,
	supabaseResults []SupabaseResult,
	awsResults []AWSResult,
) error {
	var entries []EnvEntry

	// ── Neon results ──────────────────────────────────────────────────────────
	for _, r := range neonResults {
		if r.ConnectionString == "" {
			continue
		}
		key := "NEON_DATABASE_URL_" + envKey(r.ResourceName)
		entries = append(entries, EnvEntry{
			Key:     key,
			Value:   r.ConnectionString,
			Comment: fmt.Sprintf("Neon Postgres · resource '%s' · project %s", r.ResourceName, r.ProjectID),
		})
	}

	// ── Supabase results ──────────────────────────────────────────────────────
	for _, r := range supabaseResults {
		if r.ConnectionString == "" {
			continue
		}
		key := "SUPABASE_DATABASE_URL_" + envKey(r.ResourceName)
		entries = append(entries, EnvEntry{
			Key:     key,
			Value:   r.ConnectionString,
			Comment: fmt.Sprintf("Supabase Postgres · resource '%s' · ref %s", r.ResourceName, r.ProjectRef),
		})
		// Also write the public Supabase URL (useful for client SDKs)
		if r.Host != "" {
			entries = append(entries, EnvEntry{
				Key:     "SUPABASE_URL_" + envKey(r.ResourceName),
				Value:   "https://" + r.ProjectRef + ".supabase.co",
				Comment: fmt.Sprintf("Supabase project URL · resource '%s'", r.ResourceName),
			})
		}
	}

	// ── AWS RDS results ───────────────────────────────────────────────────────
	for _, r := range awsResults {
		if r.ConnectionString == "" || r.ServiceType != "RDS" {
			continue
		}
		key := "AWS_DATABASE_URL_" + envKey(r.ResourceName)
		entries = append(entries, EnvEntry{
			Key:     key,
			Value:   r.ConnectionString,
			Comment: fmt.Sprintf("AWS RDS · resource '%s' · instance %s", r.ResourceName, r.InstanceID),
		})
	}

	if len(entries) == 0 {
		// Nothing to write — not an error, just a no-op.
		return nil
	}

	return writeEnvFile("sajon.env", entries)
}

// writeEnvFile formats entries and writes them to the given filename (mode 0600).
func writeEnvFile(filename string, entries []EnvEntry) error {
	var sb strings.Builder

	sb.WriteString("# ╔══════════════════════════════════════════════════════════╗\n")
	sb.WriteString("# ║          Auto-generated by Sajon CLI                    ║\n")
	sb.WriteString("# ║  DO NOT edit manually — run 'sajon up' to regenerate.   ║\n")
	sb.WriteString("# ╚══════════════════════════════════════════════════════════╝\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString("#\n")
	sb.WriteString("# Usage in your app:\n")
	sb.WriteString("#   Node.js   →  require('dotenv').config({ path: 'sajon.env' })\n")
	sb.WriteString("#   Python    →  load_dotenv('sajon.env')\n")
	sb.WriteString("#   Go        →  godotenv.Load(\"sajon.env\")\n")
	sb.WriteString("#   Docker    →  env_file: [sajon.env]  (in docker-compose.yml)\n")
	sb.WriteString("#\n\n")

	for _, e := range entries {
		if e.Comment != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", e.Comment))
		}
		sb.WriteString(fmt.Sprintf("%s=\"%s\"\n\n", e.Key, e.Value))
	}

	// Write atomically via temp file, then rename.
	tmpFile := filename + ".tmp"
	if err := os.WriteFile(tmpFile, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("sajon.env: write failed: %w", err)
	}
	if err := os.Rename(tmpFile, filename); err != nil {
		_ = os.Remove(tmpFile)
		return fmt.Errorf("sajon.env: rename failed: %w", err)
	}
	return nil
}

// envKey converts a Sajon resource name like "user_db" → "USER_DB",
// replacing hyphens and spaces with underscores and uppercasing everything.
func envKey(name string) string {
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, " ", "_")
	return strings.ToUpper(name)
}
